\getenv SPOTIFY_DB_USER SPOTIFY_DB_USER
\getenv SPOTIFY_DB_PASSWORD SPOTIFY_DB_PASSWORD

\echo SPOTIFY_DB_USER is :SPOTIFY_DB_USER
\echo SPOTIFY_DB_PASSWORD is :SPOTIFY_DB_PASSWORD

CREATE USER :SPOTIFY_DB_USER WITH PASSWORD :'SPOTIFY_DB_PASSWORD';

CREATE SCHEMA IF NOT EXISTS spotify_api_prod AUTHORIZATION :SPOTIFY_DB_USER;
CREATE SCHEMA IF NOT EXISTS spotify_api_stg AUTHORIZATION :SPOTIFY_DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA spotify_api_prod
GRANT ALL PRIVILEGES ON TABLES TO :SPOTIFY_DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA spotify_api_stg
GRANT ALL PRIVILEGES ON TABLES TO :SPOTIFY_DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA spotify_api_prod
GRANT USAGE, SELECT ON SEQUENCES TO :SPOTIFY_DB_USER;

-- Grant privileges on schemas to the 'postgres' user
GRANT ALL PRIVILEGES ON SCHEMA spotify_api_prod TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA spotify_api_stg TO postgres;