CREATE TABLE spotify_api_prod.DIM_MARKET 
(
    MARKET_SR_KEY BIGINT,
    NAME VARCHAR(100),
    ALPHA_2 VARCHAR(100),
    ALPHA_3 VARCHAR(100),
    COUNTRY_CODE VARCHAR(100),
    ISO_3166_2 VARCHAR(100),
    REGION VARCHAR(100),
    SUB_REGION VARCHAR(100),
    INTERMEDIATE_REGION VARCHAR(100),
    REGION_CODE VARCHAR(100),
    SUB_REGION_CODE VARCHAR(100),
    INTERMEDIATE_REGION_CODE VARCHAR(100),
    ACTIVE_FLAG VARCHAR(1),
    ETL_LOAD_DATE DATE,
    ETL_INSERT_DATE DATE 
);

CREATE UNIQUE INDEX idx_dim_market_unique_columns
ON spotify_api_prod.dim_market(alpha_2, alpha_3, country_code, iso_3166_2);