CREATE TABLE spotify_api_prod.FACT_AUDIOBOOK
(

    ID VARCHAR(100),
    MARKET_SR_KEY BIGINT
)


INSERT INTO spotify_api_prod.FACT_AUDIOBOOK 
(
ID,
MARKET_SR_KEY 
)
SELECT 
	SA.ID,
	COALESCE (DM.MARKET_SR_KEY,-1) 
	FROM spotify_api_prod.SPOTIFY_AUDIOBOOKS SA 
		LEFT OUTER JOIN spotify_api_prod.DIM_MARKET DM 
	ON SA.AVAILABLE_MARKET = DM.ALPHA_2;

 
	

